version: '3'

services:
  db:
    image: postgres:15.1-alpine
    container_name: library_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'